### 상품 생성
POST {{shop}}/api/v1/products
Content-Type: application/json

{
  "partnerId": 1,
  "categoryId": 1,
  "salePrice": 10000
}

### 상품 업데이트
PUT {{shop}}/api/v1/products/1
Content-Type: application/json

{
  "categoryId": 1,
  "salePrice": 100
}

### 상품 삭제
DELETE {{shop}}/api/v1/products/1
Content-Type: application/json

### 파트너의 상품 전체 조회
GET {{shop}}/api/v1/products/partners/1
Content-Type: application/json